esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false

    xpack.security.authc.token.enabled: false
    xpack.security.authc.api_key.enabled: false

    http.cors.enabled: false
    http.cors.allow-origin: "*"
    http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
    http.cors.allow-headers: Authorization, X-Requested-With, Content-Type, Content-Length
